describe('Testing how to play page', function() {


  describe('Leaderboard page content', function() {
    it('leaderboard page displays correct content', function() {
      cy.visit('/leaderboard')
      cy.location('pathname').should('include', 'leaderboard')
      cy.get('[alt="home-icon"]').should('be.visible')
      cy.get('[alt="plus-icon"]').should('be.visible')
      cy.get('h1').contains('CatchMe')
      cy.get('h1').contains('Leaderboard')
      cy.get('table').contains('Rank')
      cy.get('table').contains('User')
      cy.get('table').contains('Time')
      cy.get('[alt="home-icon"]').click()
      cy.get('h1').contains('CatchMe')
      cy.get('p').contains('The app that keeps you running')
    })
  })

  describe('links work', function() {
    it('return to homepage', function() {
      cy.visit('/leaderboard')
      cy.location('pathname').should('include', 'leaderboard')
      cy.get('[alt="home-icon"]').should('be.visible')
      cy.get('[alt="plus-icon"]').should('be.visible')
      cy.get('h1').contains('CatchMe')
      cy.get('h1').contains('Leaderboard')
      cy.get('table').contains('Rank')
      cy.get('table').contains('User')
      cy.get('table').contains('Time')
      cy.get('[alt="home-icon"]').click()
      cy.get('h1').contains('CatchMe')
      cy.get('p').contains('The app that keeps you running')
      cy.location('pathname').should('include', '/')
      cy.get('h1').contains('CatchMe')
      cy.get('[alt="Logo"]').should('be.visible')
      cy.get('p').contains('The app that keeps you running')
      cy.get('button').contains('How to play')
      cy.get('button').contains('Create a race')
      cy.get('button').contains('Leaderboard')
      cy.get('button').contains('Find a race')
      cy.get('p').contains('KiMaGoDa')
    })

    it('got to create race page', function() {
      cy.visit('/leaderboard')
      cy.location('pathname').should('include', 'leaderboard')
      cy.get('[alt="home-icon"]').should('be.visible')
      cy.get('[alt="plus-icon"]').should('be.visible')
      cy.get('h1').contains('CatchMe')
      cy.get('h1').contains('Leaderboard')
      cy.get('table').contains('Rank')
      cy.get('table').contains('User')
      cy.get('table').contains('Time')
      cy.get('[alt="plus-icon"]').click()
      cy.location('pathname').should('include', 'createrace')
      cy.readFile('src/components/SoundEffects/Button-sound.mp3', 'base64').then((mp3) => {
        const uri = 'data:audio/mp3;base64,' + mp3
        const audio = new Audio(uri)

        audio.play()
    })
      cy.get('h1').contains('CatchMe')
      cy.get('h2').contains('Race parameters')
      cy.get('[alt="home-icon"]').should('be.visible')
      cy.get('span').contains('10m')
      cy.get('span').contains('50m')
      cy.get('span').contains('500m')
      cy.get('span').contains('1000m')
      cy.get('span').contains('1500m')
      cy.get('span').contains('2000m')
      cy.get('p').contains('Enter your name:')
      cy.get('input').contains('Create Race')
      cy.get('p').contains('KiMaGoDa')
    })

    it('got to create race page and create a race', function() {
      cy.visit('/leaderboard')
      cy.location('pathname').should('include', 'leaderboard')
      cy.get('[alt="home-icon"]').should('be.visible')
      cy.get('[alt="plus-icon"]').should('be.visible')
      cy.get('h1').contains('CatchMe')
      cy.get('h1').contains('Leaderboard')
      cy.get('table').contains('Rank')
      cy.get('table').contains('User')
      cy.get('table').contains('Time')
      cy.get('[alt="plus-icon"]').click()
      cy.location('pathname').should('include', 'createrace')
      cy.readFile('src/components/SoundEffects/Button-sound.mp3', 'base64').then((mp3) => {
        const uri = 'data:audio/mp3;base64,' + mp3
        const audio = new Audio(uri)

        audio.play()
    })
      cy.get('h1').contains('CatchMe')
      cy.get('h2').contains('Race parameters')
      cy.get('[alt="home-icon"]').should('be.visible')
      cy.get('span').contains('10m')
      cy.get('span').contains('50m')
      cy.get('span').contains('500m')
      cy.get('span').contains('1000m')
      cy.get('span').contains('1500m')
      cy.get('span').contains('2000m')
      cy.get('p').contains('Enter your name:')
      cy.get('input').contains('Create Race')
      cy.get('p').contains('KiMaGoDa')
    })
  })

})
